# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import json
import re
import hashlib
from pathlib import Path


EXPECTED_OUTPUTS = [
    "{name}需求规格说明书.md",
    "{name}操作手册.md",
    "{name}操作手册.docx",
    "{name}操作手册.pdf",
    "{name}源代码文档.md",
    "{name}源代码文档.docx",
    "{name}源代码文档.pdf",
    "软件著作权登记申请表.md",
    "软件著作权登记申请表.docx",
]
MIN_SCREENSHOT_COUNT = 8
MAX_DUPLICATE_SCREENSHOTS = 1
MIN_SOURCE_DOC_FILE_HEADERS = 12
MIN_MANUAL_EVIDENCE_LINES = 3
EXPECTED_SOURCE_DOC_LINES = 3000
FORBIDDEN_SOURCE_DOC_TOKENS = [
    # PRD section tokens (should never appear in 源代码文档.md正文)
    "行业背景",
    "用户角色",
    "核心业务流程",
    "数据模型",
    "功能列表",
    "边界约束",
    "验收标准",
    "视觉风格关键词",
    # Common narrative/ops tokens that tend to leak from embedded HTML/README
    "版本快照",
    "发布留痕",
    "资源清单",
    "交互摘要",
    "占位页面",
    # Generic "padding" / generator artifacts
    "[padding]",
    "This file is generated by",
    # Data-dictionary / field-label catalogs (should never be used as "code padding")
    "FIELD_LABELS",
    "字段口径",
]
MAX_SOURCE_DOC_BLANK_RATIO = 0.02
FORBIDDEN_SOURCE_DOC_LINE_PATTERNS = [
    # Do not allow placeholder filler lines.
    r"^#\s*$",
]
FORM_DEV_DATE_RE = re.compile(r"(?m)^\s*[-*]?\s*开发完成日期[：:]\s*(\d{4}-\d{2}-\d{2})\s*$")
FORM_SOURCE_LINES_RE = re.compile(r"(?m)^\s*[-*]?\s*(?:源程序量|源代码量|源代码行数|代码量|代码行数)[：:]\s*(\d+)\s*(?:行)?\s*$")
MANUAL_EVIDENCE_RE = re.compile(r"(?m)^\s*(?:[-*]\s*)?(?:代码定位证据|代码位置|对应代码|实现位置)[：:].+$")
MANUAL_FIGURE_CAPTION_RE = re.compile(r"(?m)^图\d+-\d+[a-zA-Z]?\s+.+$")


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def count_source_lines(project_dir: Path) -> int:
    exts = {".py", ".js", ".mjs", ".ts", ".tsx", ".jsx", ".vue", ".css", ".html", ".sql", ".json", ".java", ".go", ".cs"}
    deny_dirs = {"node_modules", "dist", "build", "out", ".next", ".nuxt", "target", ".git", "images", "__pycache__"}
    total = 0
    for path in project_dir.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in exts:
            continue
        if any(part in deny_dirs for part in path.parts):
            continue
        total += sum(1 for line in path.read_text(encoding="utf-8", errors="ignore").splitlines() if line.strip())
    return total


def run(args: argparse.Namespace) -> int:
    project_dir = Path(args.project_dir).resolve()
    expected_form_source_lines = max(EXPECTED_SOURCE_DOC_LINES, count_source_lines(project_dir))
    report: dict[str, object] = {"passed": True, "checks": []}

    for template in EXPECTED_OUTPUTS:
        p = project_dir / template.format(name=args.requirement_name)
        ok = p.exists()
        report["checks"].append({"name": f"exists:{p.name}", "passed": ok, "message": str(p)})
        report["passed"] = report["passed"] and ok

    images_dir = project_dir / "images"
    image_files = sorted(x.name for x in images_dir.glob("*.png")) if images_dir.exists() else []
    images_ok = images_dir.exists() and len(image_files) >= MIN_SCREENSHOT_COUNT
    report["checks"].append(
        {
            "name": "images_dir",
            "passed": images_ok,
            "message": f"count={len(image_files)}, min_required={MIN_SCREENSHOT_COUNT}",
        }
    )
    report["passed"] = report["passed"] and images_ok

    # Detect screenshot duplicates (byte-identical).
    if images_dir.exists():
        hashes: dict[str, list[str]] = {}
        for name in image_files:
            p = images_dir / name
            try:
                digest = file_sha256(p)
            except OSError:
                continue
            hashes.setdefault(digest, []).append(name)
        duplicate_groups = [names for names in hashes.values() if len(names) > 1]
        duplicate_count = sum(len(g) - 1 for g in duplicate_groups)
        dup_ok = duplicate_count <= MAX_DUPLICATE_SCREENSHOTS
        report["checks"].append(
            {
                "name": "images_unique_hash",
                "passed": dup_ok,
                "message": f"duplicate_count={duplicate_count}, max_allowed={MAX_DUPLICATE_SCREENSHOTS}, groups={duplicate_groups[:5]}",
            }
        )
        report["passed"] = report["passed"] and dup_ok

    manual_md = project_dir / f"{args.requirement_name}操作手册.md"
    if manual_md.exists():
        t = manual_md.read_text(encoding="utf-8", errors="ignore")
        refs = set(re.findall(r"!\[[^\]]*\]\(images/([^)]+)\)", t))
        missing_refs = sorted(x for x in refs if not (images_dir / x).exists())
        ok = len(refs) >= MIN_SCREENSHOT_COUNT and not missing_refs
        report["checks"].append(
            {
                "name": "manual_image_refs",
                "passed": ok,
                "message": f"refs={len(refs)}, min_required={MIN_SCREENSHOT_COUNT}, missing={missing_refs}",
            }
        )
        report["passed"] = report["passed"] and ok

        evidence_count = len(MANUAL_EVIDENCE_RE.findall(t))
        evidence_ok = evidence_count >= MIN_MANUAL_EVIDENCE_LINES
        report["checks"].append(
            {
                "name": "manual_evidence_lines",
                "passed": evidence_ok,
                "message": f"count={evidence_count}, min_required={MIN_MANUAL_EVIDENCE_LINES}",
            }
        )
        report["passed"] = report["passed"] and evidence_ok

        caption_count = len(MANUAL_FIGURE_CAPTION_RE.findall(t))
        caption_ok = caption_count >= len(refs)
        report["checks"].append(
            {
                "name": "manual_figure_captions",
                "passed": caption_ok,
                "message": f"captions={caption_count}, image_refs={len(refs)}",
            }
        )
        report["passed"] = report["passed"] and caption_ok

    pipeline_report = project_dir / "pipeline_report.latest.json"
    if pipeline_report.exists():
        data = read_json(pipeline_report)
        stages = [x for x in data if isinstance(x, dict) and "stage" in x]
        failed = [x.get("stage") for x in stages if not x.get("passed", False)]
        ok = not failed
        report["checks"].append({"name": "pipeline_report", "passed": ok, "message": "ok" if ok else f"failed={failed}"})
        report["passed"] = report["passed"] and ok

    # Guard: source-code document must not contain PRD/industry narrative tokens.
    source_md = project_dir / f"{args.requirement_name}源代码文档.md"
    if source_md.exists():
        text = source_md.read_text(encoding="utf-8", errors="ignore")
        hits = [tok for tok in FORBIDDEN_SOURCE_DOC_TOKENS if tok in text]
        ok = not hits
        report["checks"].append(
            {
                "name": "source_doc_purity",
                "passed": ok,
                "message": "ok" if ok else f"forbidden_tokens={hits[:10]}",
            }
        )
        report["passed"] = report["passed"] and ok

        # Guard: "真实模块"覆盖面——至少要包含一定数量的文件头（# path）
        # and must not include pipeline scripts by default.
        headers = re.findall(r"^#\s+([^\s].+)$", text, flags=re.MULTILINE)
        header_ok = len(headers) >= MIN_SOURCE_DOC_FILE_HEADERS and not any(h.lower().startswith("scripts/") for h in headers)
        report["checks"].append(
            {
                "name": "source_doc_real_modules",
                "passed": header_ok,
                "message": f"file_headers={len(headers)}, min_required={MIN_SOURCE_DOC_FILE_HEADERS}",
            }
        )
        report["passed"] = report["passed"] and header_ok

    # Guard: source PDF should exist when source docx exists (path stability / deliverable completeness).
    source_docx = project_dir / f"{args.requirement_name}源代码文档.docx"
    source_pdf = project_dir / f"{args.requirement_name}源代码文档.pdf"
    if source_docx.exists():
        ok = source_pdf.exists()
        report["checks"].append({"name": "source_pdf_exists", "passed": ok, "message": str(source_pdf)})
        report["passed"] = report["passed"] and ok

        # Guard: avoid blank pages/blank lines by ensuring extremely low blank-line ratio.
        lines = text.splitlines()
        blank = sum(1 for ln in lines if not ln.strip())
        ratio = (blank / len(lines)) if lines else 1.0
        blanks_ok = ratio <= MAX_SOURCE_DOC_BLANK_RATIO
        report["checks"].append(
            {
                "name": "source_doc_no_blanks",
                "passed": blanks_ok,
                "message": f"blank_lines={blank}, total_lines={len(lines)}, ratio={ratio:.4f}, max_ratio={MAX_SOURCE_DOC_BLANK_RATIO}",
            }
        )
        report["passed"] = report["passed"] and blanks_ok

        # Guard: forbid placeholder filler lines like a single "#".
        bad_lines: list[str] = []
        for pat in FORBIDDEN_SOURCE_DOC_LINE_PATTERNS:
            rx = re.compile(pat)
            for ln in lines:
                if rx.match(ln):
                    bad_lines.append(pat)
                    break
        filler_ok = not bad_lines
        report["checks"].append(
            {
                "name": "source_doc_no_filler_lines",
                "passed": filler_ok,
                "message": "ok" if filler_ok else f"matched_patterns={sorted(set(bad_lines))}",
            }
        )
        report["passed"] = report["passed"] and filler_ok

    form_md = project_dir / "软件著作权登记申请表.md"
    if form_md.exists():
        form_text = form_md.read_text(encoding="utf-8", errors="ignore")
        dev_date_match = FORM_DEV_DATE_RE.search(form_text)
        dev_date_ok = bool(dev_date_match)
        report["checks"].append(
            {
                "name": "form_dev_date",
                "passed": dev_date_ok,
                "message": dev_date_match.group(1) if dev_date_match else "missing",
            }
        )
        report["passed"] = report["passed"] and dev_date_ok

        form_lines_match = FORM_SOURCE_LINES_RE.search(form_text)
        form_lines = int(form_lines_match.group(1)) if form_lines_match else None
        form_lines_ok = form_lines == expected_form_source_lines
        report["checks"].append(
            {
                "name": "form_source_line_count",
                "passed": form_lines_ok,
                "message": f"value={form_lines}, expected={expected_form_source_lines}",
            }
        )
        report["passed"] = report["passed"] and form_lines_ok

    out = Path(args.report_json).resolve() if args.report_json else None
    if out:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print("PASS" if report["passed"] else "FAIL")
    return 0 if report["passed"] else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Reusable postflight baseline checks")
    parser.add_argument("--project-dir", required=True)
    parser.add_argument("--requirement-name", required=True)
    parser.add_argument("--report-json", default="")
    return run(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
