# -*- coding: utf-8 -*-
"""
Strict validator for software copyright (软著) materials.

Design goals:
- No third-party dependencies (stdlib only).
- Fail-fast with clear reasons and file pointers.
- Enforce the workspace rule set around:
  - cross-deliverable consistency
  - anti-template / anti-hallucination checks
  - evidence-based feature traceability
  - sensitive-info leakage checks
  - source-doc purity and application-form metadata checks

Usage:
  python -X utf8 .\\workspace\\scripts\\soft_copyright_validate.py --project-root E:\\copyRight\\workspace --name 项目名 --code-root E:\\copyRight\\workspace\\some_project
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple


EXPECTED_SOURCE_DOC_LINES = 3000
MIN_MANUAL_IMAGE_REFS = 8
MIN_MANUAL_EVIDENCE_LINES = 3
MIN_MANUAL_MODAL_MENTIONS = 2
REQUIRED_MANUAL_ACTIONS = ("新增", "编辑", "删除", "查看")
FORBIDDEN_SOURCE_DOC_TOKENS = [
    "行业背景",
    "用户角色",
    "核心业务流程",
    "数据模型",
    "功能列表",
    "边界约束",
    "验收标准",
    "视觉风格关键词",
    "版本快照",
    "发布留痕",
    "资源清单",
    "交互摘要",
    "占位页面",
    "[padding]",
    "This file is generated by",
    "FIELD_LABELS",
    "字段口径",
]
TEMPLATE_TALK = [
    "界面简洁",
    "操作简单",
    "功能强大",
    "性能优越",
    "首先",
    "其次",
    "最后",
    "综上所述",
    "总而言之",
    "易用",
    "先进",
    "高效",
]
SENSITIVE_PATTERNS = [
    r"https?://",
    r"\bwww\.",
    r"\b(?:C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z):\\",
    r"\\Users\\",
    r"\b(author|created\s*at|updated\s*at|timestamp)\b",
    r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
]


@dataclass(frozen=True)
class Finding:
    level: str  # "ERROR" | "WARN"
    message: str
    file: Optional[Path] = None
    line: Optional[int] = None


NAME_LINE_RE = re.compile(r"(?m)^\s*[-*]?\s*(?:软件全称|软件名称)[：:]\s*(?P<name>[^\n\r]+)\s*$")
VERSION_LINE_RE = re.compile(r"(?m)^\s*[-*]?\s*(?:软件版本|文档版本|版本号)[：:]\s*(?P<version>V\d+(?:\.\d+)*)\s*$")
NAME_VERSION_INLINE_RE = re.compile(r"(?P<name>.+?)(?P<version>V\d+(?:\.\d+)*)")
DEV_DATE_RE = re.compile(r"(?m)^\s*[-*]?\s*开发完成日期[：:]\s*(?P<date>\d{4}-\d{2}-\d{2})\s*$")
FORM_SOURCE_LINES_RE = re.compile(r"(?m)^\s*[-*]?\s*(?:源程序量|源代码量|源代码行数|代码量|代码行数)[：:]\s*(?P<count>\d+)\s*(?:行)?\s*$")
EVIDENCE_RE = re.compile(r"(?:代码定位证据|代码位置|对应代码|实现位置)[:：]\s*(?P<evidence>.+)", flags=re.IGNORECASE)
MANUAL_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(images/([^)]+)\)")
FIGURE_CAPTION_RE = re.compile(r"^图\d+-\d+[a-zA-Z]?\s+.+", flags=re.MULTILINE)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _iter_files(root: Path, exts: Sequence[str]) -> Iterable[Path]:
    for p in root.rglob("*"):
        if p.is_file() and p.suffix.lower() in exts:
            yield p


def _line_no(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def _extract_name(text: str) -> Optional[str]:
    m = NAME_LINE_RE.search(text)
    if m:
        return m.group("name").strip()
    m = NAME_VERSION_INLINE_RE.search(text)
    if m:
        return re.sub(r"[\u3000 \t]+$", "", m.group("name").strip())
    return None


def _extract_version(text: str) -> Optional[str]:
    m = VERSION_LINE_RE.search(text)
    if m:
        return m.group("version").strip()
    m = NAME_VERSION_INLINE_RE.search(text)
    if m:
        return m.group("version").strip()
    return None


def _detect_pattern_hits(text: str, patterns: Sequence[str]) -> List[str]:
    hits: List[str] = []
    for pat in patterns:
        if re.search(pat, text, flags=re.IGNORECASE):
            hits.append(pat)
    return hits


def _detect_text_hits(text: str, phrases: Sequence[str]) -> List[str]:
    return [ph for ph in phrases if ph in text]


def _extract_evidence_lines(text: str) -> List[Tuple[int, str]]:
    out: List[Tuple[int, str]] = []
    for m in EVIDENCE_RE.finditer(text):
        ln = _line_no(text, m.start())
        out.append((ln, m.group("evidence").strip().strip("` \t")))
    return out


def _evidence_tokens(evidence: str) -> List[str]:
    raw = re.split(r"[，,;；\s]+", evidence)
    out: List[str] = []
    seen: set[str] = set()
    for token in raw:
        token = token.strip()
        if len(token) < 3:
            continue
        if token in seen:
            continue
        seen.add(token)
        out.append(token)
    return out


def _build_code_cache(code_root: Path) -> List[Tuple[Path, str]]:
    exts = {
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".vue",
        ".py",
        ".java",
        ".go",
        ".cs",
        ".rb",
        ".php",
        ".rs",
        ".kt",
        ".kts",
        ".json",
        ".yml",
        ".yaml",
        ".toml",
        ".xml",
        ".md",
        ".sql",
        ".env",
        ".ini",
        ".properties",
        ".html",
        ".css",
        ".mjs",
    }
    deny_dirs = {"node_modules", "dist", "build", "out", ".next", ".nuxt", "target", ".git"}
    cache: List[Tuple[Path, str]] = []
    for p in _iter_files(code_root, tuple(exts)):
        if any(part in deny_dirs for part in p.parts):
            continue
        try:
            cache.append((p, _read_text(p)))
        except OSError:
            continue
    return cache


def _count_source_lines_from_cache(cache: Sequence[Tuple[Path, str]]) -> int:
    total = 0
    for _, txt in cache:
        total += sum(1 for line in txt.splitlines() if line.strip())
    return total


def _expected_form_source_lines(code_cache: Sequence[Tuple[Path, str]], fallback: int = EXPECTED_SOURCE_DOC_LINES) -> int:
    actual = _count_source_lines_from_cache(code_cache)
    return actual if actual > fallback else fallback


def _search_tokens_in_code(cache: Sequence[Tuple[Path, str]], tokens: Sequence[str]) -> List[str]:
    missing: List[str] = []
    for token in tokens:
        if not any(token in txt for _, txt in cache):
            missing.append(token)
    return missing


def _validate_iso_date(text: str) -> bool:
    try:
        datetime.strptime(text, "%Y-%m-%d")
        return True
    except ValueError:
        return False


def _extract_form_dev_date(text: str) -> Optional[str]:
    m = DEV_DATE_RE.search(text)
    return m.group("date") if m else None


def _extract_form_source_lines(text: str) -> Optional[int]:
    m = FORM_SOURCE_LINES_RE.search(text)
    if not m:
        return None
    try:
        return int(m.group("count"))
    except ValueError:
        return None


def _add(findings: List[Finding], level: str, message: str, file: Optional[Path] = None, line: Optional[int] = None) -> None:
    findings.append(Finding(level, message, file, line))


def validate(
    materials_root: Path,
    a_name: str,
    code_root: Path,
    require_docx_pdf: bool,
    expected_source_doc_lines: int | None = None,
) -> List[Finding]:
    findings: List[Finding] = []

    a_dir = materials_root / a_name
    if not a_dir.exists():
        return [Finding("ERROR", f"Materials directory not found: {a_dir}")]
    if not code_root.exists():
        return [Finding("ERROR", f"Code root not found: {code_root}")]

    manual_md = a_dir / f"{a_name}操作手册.md"
    code_md = a_dir / f"{a_name}源代码文档.md"
    form_md = a_dir / "软件著作权登记申请表.md"
    img_dir = a_dir / "images"

    required = [manual_md, code_md, form_md]
    for p in required:
        if not p.exists():
            _add(findings, "ERROR", f"Missing required file: {p}", p)

    if require_docx_pdf:
        for p in [
            a_dir / f"{a_name}操作手册.docx",
            a_dir / f"{a_name}操作手册.pdf",
            a_dir / f"{a_name}源代码文档.docx",
            a_dir / f"{a_name}源代码文档.pdf",
            a_dir / "软件著作权登记申请表.docx",
        ]:
            if not p.exists():
                _add(findings, "ERROR", f"Missing required file: {p}", p)
        if not img_dir.exists() or not any(img_dir.iterdir()):
            _add(findings, "ERROR", f"Missing or empty images directory: {img_dir}", img_dir)

    if any(f.level == "ERROR" and f.message.startswith("Missing required file") for f in findings):
        return findings

    manual_txt = _read_text(manual_md)
    code_txt = _read_text(code_md)
    form_txt = _read_text(form_md)
    code_cache = _build_code_cache(code_root)

    expected_form_lines = expected_source_doc_lines or _expected_form_source_lines(code_cache, EXPECTED_SOURCE_DOC_LINES)

    # 1) Cross-deliverable consistency: name + version
    m_name, c_name, f_name = _extract_name(manual_txt), _extract_name(code_txt), _extract_name(form_txt)
    m_ver, c_ver, f_ver = _extract_version(manual_txt), _extract_version(code_txt), _extract_version(form_txt)

    if not (m_name and m_ver):
        _add(findings, "ERROR", "Cannot extract 软件名称/版本号 from 操作手册.md. 修复：补充“软件全称：… / 软件版本：V1.0”或等价正文。", manual_md)
    if not (c_name and c_ver):
        _add(findings, "ERROR", "Cannot extract 软件名称/版本号 from 源代码文档.md. 修复：补充“软件全称：… / 软件版本：V1.0”或等价正文。", code_md)
    if not (f_name and f_ver):
        _add(findings, "ERROR", "Cannot extract 软件名称/版本号 from 申请表.md. 修复：补充“软件全称：… / 软件版本：V1.0”。", form_md)

    for p, version in ((manual_md, m_ver), (code_md, c_ver), (form_md, f_ver)):
        if version and not version.startswith("V"):
            _add(findings, "ERROR", f"版本号必须使用大写 V 前缀，当前为 {version!r}。修复：统一改为如 V1.0。", p)

    if m_name and c_name and f_name and not (m_name == c_name == f_name):
        _add(findings, "ERROR", f"软件名称不一致: 手册={m_name!r}, 源码文档={c_name!r}, 申请表={f_name!r}")
    if m_ver and c_ver and f_ver and not (m_ver == c_ver == f_ver):
        _add(findings, "ERROR", f"版本号不一致: 手册={m_ver!r}, 源码文档={c_ver!r}, 申请表={f_ver!r}")

    # 2) Sensitive-info leakage + anti-template checks
    for p, txt in ((manual_md, manual_txt), (code_md, code_txt), (form_md, form_txt)):
        hits = _detect_pattern_hits(txt, SENSITIVE_PATTERNS)
        if hits:
            _add(findings, "ERROR", f"Sensitive marker(s) detected: {', '.join(hits)}。修复：移除外链、真实路径、作者/邮箱/时间戳等交付无关信息。", p)

    for p, txt in ((manual_md, manual_txt), (form_md, form_txt)):
        hits = _detect_text_hits(txt, TEMPLATE_TALK)
        if hits:
            _add(findings, "ERROR", f"Template/AI-ish phrases detected: {', '.join(hits)}。修复：改成可定位的页面、字段、按钮、规则描述。", p)

    # 3) Manual-specific checks: images, captions, actions, modal mentions
    image_refs = MANUAL_IMAGE_RE.findall(manual_txt)
    if len(image_refs) < MIN_MANUAL_IMAGE_REFS:
        _add(findings, "ERROR", f"操作手册图片引用不足：{len(image_refs)} < {MIN_MANUAL_IMAGE_REFS}。修复：补充真实界面截图与图题。", manual_md)
    if image_refs:
        for img in sorted(set(image_refs)):
            if not (img_dir / img).exists():
                _add(findings, "ERROR", f"操作手册引用了不存在的截图：images/{img}", manual_md)
        lines = manual_txt.splitlines()
        for idx, line in enumerate(lines):
            m = MANUAL_IMAGE_RE.search(line)
            if not m:
                continue
            window = "\n".join(lines[idx : min(idx + 12, len(lines))])
            if not FIGURE_CAPTION_RE.search(window):
                _add(findings, "ERROR", f"图片缺少图题说明：{m.group(1)}。修复：在图片后补“图X-Y 描述”。", manual_md, idx + 1)
    missing_actions = [action for action in REQUIRED_MANUAL_ACTIONS if action not in manual_txt]
    if missing_actions:
        _add(findings, "ERROR", f"操作手册未体现关键操作文案：{'、'.join(missing_actions)}。修复：补充真实页面中的按钮或等价动作说明。", manual_md)
    modal_mentions = len(re.findall(r"弹窗|对话框|确认(?!码)|确认删除|删除确认", manual_txt))
    if modal_mentions < MIN_MANUAL_MODAL_MENTIONS:
        _add(findings, "ERROR", f"操作手册弹窗/确认类交互说明不足：{modal_mentions} < {MIN_MANUAL_MODAL_MENTIONS}。修复：补充新增/编辑/删除确认等交互截图说明。", manual_md)

    # 4) Evidence-required checks (anti-hallucination + code correspondence)
    evidence_lines = _extract_evidence_lines(manual_txt)
    if len(evidence_lines) < MIN_MANUAL_EVIDENCE_LINES:
        _add(findings, "ERROR", f"操作手册代码定位证据不足：{len(evidence_lines)} < {MIN_MANUAL_EVIDENCE_LINES}。修复：为核心功能章节补“代码定位证据：<path>；<symbol>；<route>”。", manual_md)
    if not evidence_lines:
        return findings
    all_missing: List[Tuple[int, str, str]] = []
    for ln, ev in evidence_lines:
        tokens = _evidence_tokens(ev)
        if not tokens:
            _add(findings, "ERROR", "Empty/invalid evidence line after '代码定位证据：...'. 修复：至少提供文件路径、符号名、路由或字段名之一。", manual_md, ln)
            continue
        for token in _search_tokens_in_code(code_cache, tokens):
            all_missing.append((ln, ev, token))
    for ln, ev, token in all_missing[:20]:
        _add(findings, "ERROR", f"Evidence token not found in codebase: token={token!r}; evidence_line={ev!r}。修复：改成真实存在的路径、类名、函数名、路由或字段名。", manual_md, ln)
    if len(all_missing) > 20:
        _add(findings, "ERROR", f"... and {len(all_missing) - 20} more missing evidence tokens.", manual_md)

    # 5) Source-doc purity checks
    forbidden_hits = [tok for tok in FORBIDDEN_SOURCE_DOC_TOKENS if tok in code_txt]
    if forbidden_hits:
        _add(findings, "ERROR", f"源代码文档混入无关内容：{', '.join(forbidden_hits[:10])}。修复：通过 source_doc_rules.json 或项目过滤规则清理非代码叙述。", code_md)
    if "[padding]" in code_txt:
        _add(findings, "ERROR", "源代码文档包含可见占位符 [padding]。修复：改为真实代码行补齐。", code_md)

    # 6) Application-form checks
    dev_date = _extract_form_dev_date(form_txt)
    if not dev_date:
        _add(findings, "ERROR", "申请表缺少“开发完成日期”。修复：补充 YYYY-MM-DD 格式日期。", form_md)
    elif not _validate_iso_date(dev_date):
        _add(findings, "ERROR", f"申请表开发完成日期格式非法：{dev_date!r}。修复：改为 YYYY-MM-DD。", form_md)

    form_lines = _extract_form_source_lines(form_txt)
    if form_lines is None:
        _add(findings, "ERROR", f"申请表缺少“源程序量”。修复：补充“源程序量：{expected_form_lines}”。", form_md)
    elif form_lines != expected_form_lines:
        _add(findings, "ERROR", f"申请表源程序量与实际代码总行数口径不一致：{form_lines} != {expected_form_lines}。修复：统一为 {expected_form_lines}。", form_md)

    # 7) Basic source-doc module sanity
    headers = re.findall(r"^#\s+([^\s].+)$", code_txt, flags=re.MULTILINE)
    if len(headers) < 12:
        _add(findings, "WARN", f"源代码文档文件头偏少：{len(headers)} < 12。可能缺少真实模块覆盖。", code_md)
    if any(h.lower().startswith("scripts/") for h in headers):
        _add(findings, "WARN", "源代码文档文件头出现 scripts/ 开头项，可能混入过多流水线脚本。", code_md)

    return findings


def main(argv: Sequence[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", required=True, help="Root folder that contains the {A}/ materials directory.")
    ap.add_argument("--name", required=True, help="需求名称 {A} (also materials subdirectory name).")
    ap.add_argument("--code-root", required=True, help="Codebase root used for 'locatable in code' checks.")
    ap.add_argument("--require-docx-pdf", action="store_true", help="Also require docx/pdf and images/ existence.")
    ap.add_argument("--expected-source-doc-lines", type=int, default=0, help="Optional override for expected '源程序量'. Default: auto-calc as max(3000, actual code lines).")
    ns = ap.parse_args(argv)

    findings = validate(
        materials_root=Path(ns.project_root),
        a_name=ns.name,
        code_root=Path(ns.code_root),
        require_docx_pdf=bool(ns.require_docx_pdf),
        expected_source_doc_lines=(int(ns.expected_source_doc_lines) or None),
    )
    errors = [f for f in findings if f.level == "ERROR"]
    warns = [f for f in findings if f.level == "WARN"]

    def fmt(f: Finding) -> str:
        loc = ""
        if f.file:
            loc = str(f.file)
            if f.line:
                loc += f":{f.line}"
            loc += ": "
        return f"[{f.level}] {loc}{f.message}"

    for f in findings:
        print(fmt(f))

    if errors:
        print(f"FAIL: {len(errors)} error(s), {len(warns)} warning(s)")
        return 2
    print(f"PASS: {len(warns)} warning(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
